USE SCHEMA TUTORIAL_DB.NORQUEST;
USE WAREHOUSE TUTORIAL_WH;
USE ROLE USERADMIN;

CREATE USER NORQUEST_SVC
PASSWORD = '------' 
TYPE = LEGACY_SERVICE
DEFAULT_WAREHOUSE = TUTORIAL_WH
DEFAULT_NAMESPACE = TUTORIAL_DB.NORQUEST;

USE ROLE SECURITYADMIN;
grant role sysadmin to USER NORQUEST_SVC;







